version: 1.2.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore Judge\Judge.sln
build:
  publish_wap: true
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - Database
    - Checker