version: 1.2.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true
before_build:
- cmd: nuget restore Judge\Judge.sln
build:
  publish_wap: true
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - Database
    - Checker
artifacts:
- path: '*.zip'
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: Gg/D4oFtmyEjhqq9AD3dMXpkvuzv4vcY+RS5H/5a2wGNo4ryI+yF8kikK+95Wdsr
  on:
    appveyor_repo_tag: true