version: 1.2.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore Judge\Judge.sln
build:
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - Database
    - Checker
after_build:
- Judge\after_build.bat
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: Gg/D4oFtmyEjhqq9AD3dMXpkvuzv4vcY+RS5H/5a2wGNo4ryI+yF8kikK+95Wdsr
  on:
    appveyor_repo_tag: true