//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Judge.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Judge.Application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чек-поинт.
        /// </summary>
        public static string ContestCheckPointTime {
            get {
                return ResourceManager.GetString("ContestCheckPointTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        public static string ContestFinish {
            get {
                return ResourceManager.GetString("ContestFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыт.
        /// </summary>
        public static string ContestIsOpened {
            get {
                return ResourceManager.GetString("ContestIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string ContestName {
            get {
                return ResourceManager.GetString("ContestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        public static string ContestStart {
            get {
                return ResourceManager.GetString("ContestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен.
        /// </summary>
        public static string ContestStatusFinished {
            get {
                return ResourceManager.GetString("ContestStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланирован.
        /// </summary>
        public static string ContestStatusPlanned {
            get {
                return ResourceManager.GetString("ContestStatusPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет....
        /// </summary>
        public static string ContestStatusStarted {
            get {
                return ResourceManager.GetString("ContestStatusStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корреткный Email.
        /// </summary>
        public static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничение по памяти в байтах.
        /// </summary>
        public static string MemoryLimitBytes {
            get {
                return ResourceManager.GetString("MemoryLimitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один язык на задачу.
        /// </summary>
        public static string OneLanguagePerTask {
            get {
                return ResourceManager.GetString("OneLanguagePerTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан лейбл задачи.
        /// </summary>
        public static string TaskHaveNoLabel {
            get {
                return ResourceManager.GetString("TaskHaveNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна в общем списке задач.
        /// </summary>
        public static string TaskIsOpened {
            get {
                return ResourceManager.GetString("TaskIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лейблы задач повторяются.
        /// </summary>
        public static string TaskLabelsHaveDuplicates {
            get {
                return ResourceManager.GetString("TaskLabelsHaveDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи повторяются.
        /// </summary>
        public static string TasksHaveDuplicates {
            get {
                return ResourceManager.GetString("TasksHaveDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание задачи.
        /// </summary>
        public static string TaskStatement {
            get {
                return ResourceManager.GetString("TaskStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с тестами.
        /// </summary>
        public static string TestsFolder {
            get {
                return ResourceManager.GetString("TestsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничение по времени в мс..
        /// </summary>
        public static string TimeLimitMilliseconds {
            get {
                return ResourceManager.GetString("TimeLimitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
